### ISSUE TITLE
What style to use

### ISSUE THREAD

**Issue by ghost** [Pantherbotics/FRC2016_Stronghold#2]
Do we want a command based robot, or a simple multi-threaded robot like last year.

**Comment by gravityfox** [comment]
Define "Command Based"

**Comment by ghost** [comment]
This isn't the limitations, but this gives a basic example: https://wpilib.screenstepslive.com/s/4485/m/13809/l/241892-what-is-command-based-programming

Essentially it allows you to make more of an event based system.

**Comment by rodsouza9** [comment]
What would be the advantage of doing command based.

**Comment by ghost** [comment]
That page kinda explains it.... It's a state based system, and I modular...

**Comment by ghost** [comment]
We are doing CommandBased... End of discussion for now!
